init:
  - git config --global core.autocrlf true
branches:
  only:
    - master
    - release
    - dev
    - /^(.*\/)?ci-.*$/
build_script:
  - build.cmd --quiet verify
artifacts:
  - path: '**\*.nupkg'

clone_depth: 1
test: off
deploy: off